"""
Strategy Base Class
===================

Abstract base class for all trading strategies in the Layer 0 qualification engine.
Provides a standardized interface for strategy development, backtesting, and analysis.
"""

from abc import ABC, abstractmethod
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple, Any, Union
from enum import Enum
import pandas as pd
import numpy as np
from datetime import datetime


class SignalType(Enum):
    """Trade signal types."""
    BUY = 1
    SELL = -1
    HOLD = 0


class TradeDirection(Enum):
    """Trade direction."""
    LONG = 1
    SHORT = -1


@dataclass
class Trade:
    """
    Represents a single trade.
    
    Attributes:
        entry_time: Trade entry timestamp
        exit_time: Trade exit timestamp (None if open)
        entry_price: Entry price
        exit_price: Exit price (None if open)
        direction: Trade direction (1 for long, -1 for short)
        stop_loss: Stop loss price
        take_profit: Take profit price
        size: Position size
        asset: Asset symbol
        strategy: Strategy name
        granularity: Timeframe of entry signal
        bars_held: Number of bars position was held
        pnl: Profit/loss in account currency
        pnl_pips: Profit/loss in pips
        r_multiple: P/L expressed in R multiples
        exit_reason: Why the trade exited
    """
    entry_time: datetime
    entry_price: float
    direction: int
    stop_loss: float
    take_profit: float
    asset: str
    strategy: str
    granularity: str
    size: float = 1.0
    exit_time: Optional[datetime] = None
    exit_price: Optional[float] = None
    bars_held: int = 0
    pnl: float = 0.0
    pnl_pips: float = 0.0
    r_multiple: float = 0.0
    exit_reason: str = ""
    
    @property
    def is_open(self) -> bool:
        """Check if trade is still open."""
        return self.exit_time is None
    
    @property
    def is_winner(self) -> bool:
        """Check if trade was profitable."""
        return self.pnl > 0
    
    @property
    def risk_amount(self) -> float:
        """Calculate risk amount in price terms."""
        return abs(self.entry_price - self.stop_loss)
    
    @property
    def reward_amount(self) -> float:
        """Calculate reward amount in price terms."""
        return abs(self.take_profit - self.entry_price)
    
    @property
    def risk_reward_ratio(self) -> float:
        """Calculate risk/reward ratio."""
        risk = self.risk_amount
        reward = self.reward_amount
        if risk == 0:
            return 0
        return reward / risk


@dataclass
class StrategyConfig:
    """
    Strategy configuration parameters.
    
    Attributes:
        name: Strategy name
        description: Strategy description
        version: Strategy version
        author: Strategy author
        assets: List of assets to trade
        granularities: List of timeframes to trade
        use_multi_timeframe: Whether to use MTF confluence
        primary_granularity: Primary entry timeframe
        confirmation_granularity: Confirmation timeframe
        macro_granularity: Macro trend timeframe (e.g., D1)
        atr_period: ATR calculation period
        stop_loss_atr: Stop loss as ATR multiple
        take_profit_atr: Take profit as ATR multiple
        max_bars_hold: Maximum bars to hold a position
        min_bars_hold: Minimum bars to hold a position
        require_trend_alignment: Require alignment with macro trend
        session_filter: Apply session-based filtering
        volatility_filter: Apply volatility-based filtering
    """
    name: str
    description: str = ""
    version: str = "1.0.0"
    author: str = ""
    assets: List[str] = field(default_factory=lambda: ["EUR_USD", "GBP_USD", "USD_JPY"])
    granularities: List[str] = field(default_factory=lambda: ["H4", "H1"])
    use_multi_timeframe: bool = True
    primary_granularity: str = "H4"
    confirmation_granularity: str = "H1"
    macro_granularity: str = "D1"
    atr_period: int = 14
    stop_loss_atr: float = 1.5
    take_profit_atr: float = 2.5
    max_bars_hold: int = 50
    min_bars_hold: int = 2
    require_trend_alignment: bool = True
    session_filter: bool = False
    volatility_filter: bool = True
    max_atr_percentile: float = 90.0  # Reject trades when ATR > 90th percentile


@dataclass
class Signal:
    """
    Trading signal generated by a strategy.
    
    Attributes:
        timestamp: Signal timestamp
        asset: Asset symbol
        signal_type: Type of signal (BUY, SELL, HOLD)
        direction: 1 for long, -1 for short, 0 for no signal
        price: Entry price
        stop_loss: Recommended stop loss
        take_profit: Recommended take profit
        confidence: Signal confidence (0-1)
        metadata: Additional signal metadata
    """
    timestamp: datetime
    asset: str
    signal_type: SignalType
    direction: int
    price: float
    stop_loss: float
    take_profit: float
    confidence: float = 0.5
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def to_dict(self) -> Dict[str, Any]:
        """Convert signal to dictionary."""
        return {
            'timestamp': self.timestamp,
            'asset': self.asset,
            'signal_type': self.signal_type.name,
            'direction': self.direction,
            'price': self.price,
            'stop_loss': self.stop_loss,
            'take_profit': self.take_profit,
            'confidence': self.confidence,
            'metadata': self.metadata
        }


class StrategyBase(ABC):
    """
    Abstract base class for all trading strategies.
    
    All strategies must inherit from this class and implement:
    - calculate_indicators(): Calculate strategy-specific indicators
    - generate_signals(): Generate buy/sell signals
    - get_entry_conditions(): Return entry condition descriptions
    - get_exit_conditions(): Return exit condition descriptions
    """
    
    def __init__(self, config: StrategyConfig):
        """
        Initialize strategy with configuration.
        
        Args:
            config: Strategy configuration
        """
        self.config = config
        self.indicators: Dict[str, pd.DataFrame] = {}
        self.signals: List[Signal] = []
        self.trades: List[Trade] = []
        self.data: Dict[str, Dict[str, pd.DataFrame]] = {}  # asset -> granularity -> df
        
    @abstractmethod
    def calculate_indicators(self, df: pd.DataFrame, asset: str, granularity: str) -> pd.DataFrame:
        """
        Calculate strategy-specific indicators.
        
        Args:
            df: OHLCV DataFrame with columns: Open, High, Low, Close, Volume
            asset: Asset symbol
            granularity: Timeframe
            
        Returns:
            DataFrame with added indicator columns
        """
        pass
    
    @abstractmethod
    def generate_signals(self, df: pd.DataFrame, asset: str, granularity: str) -> pd.Series:
        """
        Generate trading signals.
        
        Args:
            df: DataFrame with indicators
            asset: Asset symbol
            granularity: Timeframe
            
        Returns:
            Series with signal values (1=buy, -1=sell, 0=hold)
        """
        pass
    
    @abstractmethod
    def get_entry_conditions(self) -> Dict[str, str]:
        """
        Get entry condition descriptions.
        
        Returns:
            Dictionary mapping timeframe to condition description
        """
        pass
    
    @abstractmethod
    def get_exit_conditions(self) -> Dict[str, str]:
        """
        Get exit condition descriptions.
        
        Returns:
            Dictionary mapping exit type to condition description
        """
        pass
    
    def prepare_data(self, data: Dict[str, Dict[str, pd.DataFrame]]) -> None:
        """
        Prepare data by calculating indicators for all assets and timeframes.
        
        Args:
            data: Nested dict of asset -> granularity -> DataFrame
        """
        self.data = data
        
        for asset in data:
            self.indicators[asset] = {}
            for granularity in data[asset]:
                df = data[asset][granularity].copy()
                df = self.calculate_indicators(df, asset, granularity)
                if asset not in self.indicators:
                    self.indicators[asset] = {}
                self.indicators[asset][granularity] = df
    
    def get_signals(self, asset: str, granularity: str) -> pd.Series:
        """
        Get signals for a specific asset and timeframe.
        
        Args:
            asset: Asset symbol
            granularity: Timeframe
            
        Returns:
            Series with signal values
        """
        if asset not in self.indicators or granularity not in self.indicators[asset]:
            raise ValueError(f"No indicators found for {asset} {granularity}")
        
        df = self.indicators[asset][granularity]
        return self.generate_signals(df, asset, granularity)
    
    def calculate_stop_loss(self, df: pd.DataFrame, direction: int, 
                           entry_price: float, asset: str) -> float:
        """
        Calculate stop loss price.
        
        Args:
            df: DataFrame with ATR calculated
            direction: Trade direction (1=long, -1=short)
            entry_price: Entry price
            asset: Asset symbol
            
        Returns:
            Stop loss price
        """
        if 'ATR' not in df.columns:
            from .indicators import atr
            df['ATR'] = atr(df['High'], df['Low'], df['Close'], self.config.atr_period)
        
        atr_val = df['ATR'].iloc[-1]
        stop_distance = atr_val * self.config.stop_loss_atr
        
        if direction == 1:  # Long
            return entry_price - stop_distance
        else:  # Short
            return entry_price + stop_distance
    
    def calculate_take_profit(self, df: pd.DataFrame, direction: int, 
                             entry_price: float, asset: str) -> float:
        """
        Calculate take profit price.
        
        Args:
            df: DataFrame with ATR calculated
            direction: Trade direction (1=long, -1=short)
            entry_price: Entry price
            asset: Asset symbol
            
        Returns:
            Take profit price
        """
        if 'ATR' not in df.columns:
            from .indicators import atr
            df['ATR'] = atr(df['High'], df['Low'], df['Close'], self.config.atr_period)
        
        atr_val = df['ATR'].iloc[-1]
        profit_distance = atr_val * self.config.take_profit_atr
        
        if direction == 1:  # Long
            return entry_price + profit_distance
        else:  # Short
            return entry_price - profit_distance
    
    def check_volatility_filter(self, df: pd.DataFrame) -> bool:
        """
        Check if current volatility is acceptable for trading.
        
        Args:
            df: DataFrame with ATR calculated
            
        Returns:
            True if volatility is acceptable
        """
        if not self.config.volatility_filter:
            return True
        
        if 'ATR' not in df.columns:
            return True
        
        # Vectorized ATR percentile calculation
        atr_series = df['ATR']
        if len(atr_series) < 100:
            return True
        
        rolling_rank = atr_series.rolling(window=100).rank(pct=True)
        current_percentile = rolling_rank.iloc[-1]
        return current_percentile <= (self.config.max_atr_percentile / 100)
    
    def get_required_warmup_bars(self) -> int:
        """
        Get the number of warmup bars required for indicators.
        
        Returns:
            Number of bars needed before generating valid signals
        """
        return 200  # Default, override in subclasses if needed
    
    def validate_config(self) -> List[str]:
        """
        Validate strategy configuration.
        
        Returns:
            List of validation errors (empty if valid)
        """
        errors = []
        
        if not self.config.name:
            errors.append("Strategy name is required")
        
        if self.config.stop_loss_atr <= 0:
            errors.append("Stop loss ATR multiplier must be positive")
        
        if self.config.take_profit_atr <= 0:
            errors.append("Take profit ATR multiplier must be positive")
        
        if self.config.max_bars_hold <= self.config.min_bars_hold:
            errors.append("max_bars_hold must be greater than min_bars_hold")
        
        return errors
    
    def get_strategy_info(self) -> Dict[str, Any]:
        """
        Get strategy information for reporting.
        
        Returns:
            Dictionary with strategy metadata
        """
        return {
            'name': self.config.name,
            'description': self.config.description,
            'version': self.config.version,
            'author': self.config.author,
            'assets': self.config.assets,
            'granularities': self.config.granularities,
            'use_multi_timeframe': self.config.use_multi_timeframe,
            'primary_granularity': self.config.primary_granularity,
            'confirmation_granularity': self.config.confirmation_granularity,
            'macro_granularity': self.config.macro_granularity,
            'entry_conditions': self.get_entry_conditions(),
            'exit_conditions': self.get_exit_conditions(),
            'stop_loss_atr': self.config.stop_loss_atr,
            'take_profit_atr': self.config.take_profit_atr,
        }


class MultiTimeframeStrategy(StrategyBase):
    """
    Base class for strategies that use multi-timeframe confluence.
    """
    
    def __init__(self, config: StrategyConfig):
        super().__init__(config)
        if not config.use_multi_timeframe:
            raise ValueError("MultiTimeframeStrategy requires use_multi_timeframe=True")
    
    def get_macro_trend(self, asset: str) -> int:
        """
        Get macro trend direction from highest timeframe.
        
        Args:
            asset: Asset symbol
            
        Returns:
            1 for uptrend, -1 for downtrend, 0 for neutral
        """
        macro_gran = self.config.macro_granularity
        
        if asset not in self.indicators or macro_gran not in self.indicators[asset]:
            return 0
        
        df = self.indicators[asset][macro_gran]
        
        # Default: use EMA alignment
        if 'EMA_50' in df.columns and 'EMA_200' in df.columns:
            if df['EMA_50'].iloc[-1] > df['EMA_200'].iloc[-1]:
                return 1
            elif df['EMA_50'].iloc[-1] < df['EMA_200'].iloc[-1]:
                return -1
        
        return 0
    
    def check_timeframe_alignment(self, asset: str, direction: int) -> bool:
        """
        Check if multiple timeframes align with trade direction.
        
        Args:
            asset: Asset symbol
            direction: Proposed trade direction
            
        Returns:
            True if timeframes align
        """
        if not self.config.require_trend_alignment:
            return True
        
        macro_trend = self.get_macro_trend(asset)
        
        # If macro trend is defined, trade must align with it
        if macro_trend != 0 and direction != macro_trend:
            return False
        
        return True
